import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { ResidentReport } from "@/services/report";

interface PdfOptions {
  title: string;
  data: ResidentReport[];
  generatedBy: string;
}

export function generateResidentReport(options: PdfOptions): void {
  const { title, data, generatedBy } = options;

  const doc = new jsPDF("l", "mm", "a4"); // Landscape A4

  // Header
  doc.setFontSize(10);
  doc.text("Republic of the Philippines", 148, 15, { align: "center" });
  doc.text("City of Manila", 148, 20, { align: "center" });
  doc.setFontSize(12);
  doc.text("BARANGAY 418 ZONE 43 DISTRICT IV", 148, 27, { align: "center" });
  doc.setFontSize(10);
  doc.text("Office of the Barangay Chairman", 148, 32, { align: "center" });

  // Title
  doc.setFontSize(14);
  doc.text(title, 148, 45, { align: "center" });

  // Table
  const tableData = data.map((r) => [
    r.no.toString(),
    r.lastName,
    r.firstName,
    r.middleName,
    r.age.toString(),
    r.sex,
    r.address,
    r.contact,
    r.status,
    "", // Signature column (empty)
  ]);

  autoTable(doc, {
    startY: 55,
    head: [["No.", "Last Name", "First Name", "Middle Name", "Age", "Sex", "Address", "Contact", "Status", "Signature"]],
    body: tableData,
    styles: {
      fontSize: 8,
      cellPadding: 2,
    },
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: 255,
      fontStyle: "bold",
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 30 },
      2: { cellWidth: 30 },
      3: { cellWidth: 25 },
      4: { cellWidth: 12 },
      5: { cellWidth: 12 },
      6: { cellWidth: 50 },
      7: { cellWidth: 25 },
      8: { cellWidth: 18 },
      9: { cellWidth: 25 },
    },
    margin: { top: 55, left: 10, right: 10 },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.height;

    doc.setFontSize(8);
    doc.text(`Total Count: ${data.length}`, 10, pageHeight - 15);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 10, pageHeight - 10);
    doc.text(`Generated by: ${generatedBy}`, 148, pageHeight - 10, { align: "center" });
  }

  // Download
  doc.save(`${title.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`);
}
