import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { ResidentReport } from "@/services/report";

interface PdfOptions {
  title: string;
  data: ResidentReport[];
  generatedBy: string;
}

export function generateResidentReport(options: PdfOptions): void {
  const { title, data, generatedBy } = options;

  const doc = new jsPDF("p", "mm", "a4"); // Portrait A4

  // Header
  const pageWidth = doc.internal.pageSize.width;
  doc.setFontSize(10);
  doc.text("Republic of the Philippines", pageWidth / 2, 15, { align: "center" });
  doc.text("City of Manila", pageWidth / 2, 20, { align: "center" });
  doc.setFontSize(12);
  doc.text("BARANGAY 418 ZONE 43 DISTRICT IV", pageWidth / 2, 27, { align: "center" });
  doc.setFontSize(10);
  doc.text("Office of the Barangay Chairman", pageWidth / 2, 32, { align: "center" });

  // Title
  doc.setFontSize(14);
  doc.text(title, pageWidth / 2, 45, { align: "center" });

  // Table - Combined Name column
  const tableData = data.map((r) => [
    r.no.toString(),
    `${r.lastName}, ${r.firstName} ${r.middleName}`,
    r.sex,
    r.address,
    "", // Signature column (empty)
  ]);

  autoTable(doc, {
    startY: 55,
    head: [["No.", "Name", "Sex", "Address", "Signature"]],
    body: tableData,
    styles: {
      fontSize: 8,
      cellPadding: 2,
    },
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: 255,
      fontStyle: "bold",
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 70 },
      2: { cellWidth: 15 },
      3: { cellWidth: 60 },
      4: { cellWidth: 25 },
    },
    margin: { top: 55, left: 10, right: 10 },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.height;

    doc.setFontSize(8);
    doc.text(`Total Count: ${data.length}`, 10, pageHeight - 15);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 10, pageHeight - 10);
    doc.text(`Generated by: ${generatedBy}`, pageWidth - 10, pageHeight - 10, { align: "right" });
  }

  // Download
  doc.save(`${title.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`);
}
