nodeLinker: hoisted
blockExoticSubdeps: false
packages:
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  core-js: true
  electron: true
  electron-winstaller: true
  esbuild: true
  prisma: true
