export { api } from "./api";
export { authService } from "./auth";
export { residentsService } from "./residents";
export { householdsService } from "./households";
export { familiesService } from "./families";
export { documentsService } from "./documents";
export { usersService } from "./users";
export { activityLogsService } from "./activityLogs";
export { dashboardService } from "./dashboard";
export type { ResidentDemographics } from "./dashboard";
export { settingsService } from "./settings";
export type { BarangaySettings } from "./settings";
